export const TOUCHED_STATES = {
  NOT_TOUCHED: "NOT_TOUCHED",
  TOUCHED_FIRST_TIME: "TOUCHED_FIRST_TIME",
  TOUCHED_OK: "TOUCHED_OK",
}

export const STATES_FORM = {
  FIRST_STAGE: 33,
  SECOND_STAGE: 66,
  THIRD_STAGE: 100,
}