export const TYPES_FORM_FINANCING = {
    CHANGE_COMPANY_NAME: 'CHANGE_COMPANY_NAME',
    CHANGE_NIT: 'CHANGE_NIT',
    CHANGE_DATE_OF_FUNDATION: 'CHANGE_DATE_OF_FUNDATION',
    CHANGE_CITY_CONSTITUTION: 'CHANGE_CITY_CONSTITUTION',
    CHANGE_KW_INSTALLED: 'CHANGE_KW_INSTALLED',
    CHANGE_NUMBER_CLIENTES: 'CHANGE_NUMBER_CLIENTES',
    CHANGE_ACOSOL_ASSOCIATE: 'CHANGE_ACOSOL_ASSOCIATE',
    CHANGE_INFLUENCY_CITY: 'CHANGE_INFLUENCY_CITY',
    CHANGE_EMAIL: 'CHANGE_EMAIL',
    CHANGE_PHONE_NUMBER: 'CHANGE_PHONE_NUMBER',
    CHANGE_WEB_PAGE: 'CHANGE_WEB_PAGE',
    CHANGE_NUMERO_CUOTAS: 'CHANGE_NUMERO_CUOTAS',
  }