export const TYPES_FORM_SAVING ={
  CHANGE_INVOICE_VALUE: "CHANGE_INVOICE_VALUE",
  CHANGE_STRATUM: "CHANGE_STRATUM",
  CHANGE_HOURS_WITHOUT_ENERGY: "CHANGE_HOURS_WITHOUT_ENERGY",
  CHANGE_DEPARTMENT: "CHANGE_DEPARTMENT",
  CHANGE_MUNICIPALITY: "CHANGE_MUNICIPALITY",
  CHANGE_LOCALITY: "CHANGE_LOCALITY",
  CHANGE_RURAL: "CHANGE_RURAL"
}